### ISSUE TITLE
Configure prints "FreeImage not found" and "PVRTexLib not found" even though all git submodules are present

### ISSUE THREAD

**Issue by yurivict** [akb825/Cuttlefish#14]
```
===>  Configuring for cuttlefish-texture-compressor-2.6.0
===>  Performing out-of-source build
/bin/mkdir -p /disk-samsung/freebsd-ports/misc/cuttlefish/work/.build
-- The C compiler identification is Clang 13.0.0
-- The CXX compiler identification is Clang 13.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Found Threads: TRUE  
-- Looking for FreeImage
FreeImage not found
PVRTexLib not found
-- Configuring done
-- Generating done
```

FreeBSD 13.1

**Comment by akb825** [comment]
FreeImage first checks for a version on your system, and if not found it will build from the submodule. This message is a little confusing, though, and I can make it more descriptive.

PVRTexLib unfortunately is a closed source library, and is the only option for creating PVRTC textures. Since you are building on FreeBSD, it won't be able to use that library and PVRTC support will be disabled.

BTW, I noticed in your port you're manually setting compile flags for PPC. I patched the dependency that the flags were used for to automatically detect the CPU at compile time so that should no longer be necessary.

**Comment by yurivict** [comment]
> BTW, I noticed in your port you're manually setting compile flags for PPC. I patched the dependency that the flags were used for to automatically detect the CPU at compile time so that should no longer be necessary.

Someone else added the ```powerpc*``` check. I'll remove remove it then. Thanks for letting me know.
