### ISSUE TITLE
Failure to write when output folder doesn't exist.

### ISSUE THREAD

**Issue by alecazam** [akb825/Cuttlefish#2]
Many tools that process textures often have subfolders that need to be created.  I noted that cuttlefish was failing to write on these cases when I'd wipe the parent directory.  It would be useful to have cuttlefish build subdirectories if they don't exist when providing an output path to simplify scripting and repeatability of texture processing.

I was trying cuttlefish after switching off PVRTexToolCLI, and this was one notable difference and breakage in the texture processing between these utilities.

This is the basic source to create the full path of directories and then open a file.  This could be split out into a mkdir call, and the fopen call could just proceed normally then.  Current behavior is a rather cryptic failure to write message,, so so I thought the encoder was failing.

```
// https://stackoverflow.com/questions/7430248/creating-a-new-directory-in-c

void rek_mkdir(char *path) {
    char *sep = strrchr(path, '/');
    if(sep != NULL) {
        *sep = 0;
        rek_mkdir(path);
        *sep = '/';
    }
    if(mkdir(path, 0777) && errno != EEXIST)
        printf("error while trying to create '%s'\n%m\n", path); 
}

FILE *fopen_mkdir(char *path, char *mode) {
    char *sep = strrchr(path, '/');
    if(sep) { 
        char *path0 = strdup(path);
        path0[ sep - path ] = 0;
        rek_mkdir(path0);
        free(path0);
    }
    return fopen(path,mode);
}
```

**Comment by alecazam** [comment]
Workaround for now is in scripts to call this before calling cuttlefish.

mkdir -p "$(dirname "$output")"

**Comment by akb825** [comment]
What version of PVRTexToolCLI and on what operating system were you running? When running PVRTexToolCLI 4.23 (from the 2019.R2 install) on Linux, I get the following error message if the parent directory doesn't exist:

> Error: Unable to save texture as requested format, please check the format being used is supported.

It's been my impression that tools that output a single file by path (as opposed to providing an output directory) error out if the parent directory doesn't exist. To verify this, I tried a few other tools such as gcc and another texture conversion tool I found online, and none of them create the parent directory for you.

While I agree it can be useful, it's also good practice to make as few changes to the filesystem as possible inside the tool. Since the general trend among similar tools is to not create the parent directories, I would be hesitant to do so for cuttlefish.

**Comment by alecazam** [comment]
Yeah, I found most tools don't create directories including PVTexToolCLI.   I was working with a script that was failing when I switched to Cuttlefish, but I found out later it needed that directory creation for PVRTexToolCLI as well.  There's a workaround, but it means more scripting instead of keeping it all in C++.  EtcTool does have some directory creation calls inside it.

**Comment by akb825** [comment]
I feel it's better to keep consistent with the conventions used with other command-line utilities, since it offers fewer surprises when working with multiple tools. While it can be useful to create the parent directories for you, it can also be useful to be given an error if you passed it the wrong directory name. (e.g. you get an error if you have a typo in the directory name rather than creating the directory)

Rather than calling `mkdir -p "$(dirname "$output")"` before invoking Cuttlefish for each texture, I would recommend creating your directory structure at the start of the build process. That is pretty common practice, will provide some protections if you accidentally put something in the wrong place, and will also work more gracefully when integrating other tools into your build process.

**Comment by alecazam** [comment]
I this case I want to let the artists to organize their content they way they feel best, so new folders could appear/disappear at any time.  Draconian measures to stuff all textures into a flat hierarchy aren't always best, but certainly easier for the engine to deal with then.

**Comment by akb825** [comment]
I was thinking along the lines of building an asset package, but in the case of a tool for artists I agree it would ideally follow the directory structure of their source images.

Since I think the default behavior should stay as it is, as a compromise I can add a command-line argument to have Cuttlefish create the parent directory for you.

**Comment by akb825** [comment]
You can now use the `--create-dir` command-line argument in version 2.1.0.
