### ISSUE TITLE
Artifacts in alpha channel with BC1_RGB compression

### ISSUE THREAD

**Issue by Froyok** [akb825/Cuttlefish#20]
Hi,

I have the following image without any alpha (fully white) which I wanted to convert into BC1_RGB. However when I do so I end-up with blocky artifacts in the Alpha channel/component of the texture. Using BC1_RGBA solves the issue. I'm not sure if that's the intended behavior, I would have expected something fully white or black, and not an hybrid.

(I'm checking out my files in RenderDoc.)

Source image:
![train_debug_RGB](https://github.com/akb825/Cuttlefish/assets/6290387/c3796362-84fb-42e2-9fa1-d68736e33116)

DDS image is produced with the following command:
`cuttlefish --input "train_debug_RGB.png" --file-format dds --mipmap --format BC1_RGB --output "train_debug_RGB.dds"`

When I check the alpha of the DDS file in RenderDoc this is what I see:
![dds_artifacts](https://github.com/akb825/Cuttlefish/assets/6290387/c0b93a3d-6e51-445b-ab9f-f09ce5f93b12)

As I far I can see, my PNG file doesn't any alpha/transparency (other than fully white, so I'm considering it's opaque). So I don't understand why some blocks would end-up being 0 and not 255. I also noticed the issue on older versions as well, so it doesn't seem to be a regression.

---

Technical details:

- **Cuttlefish version**: 2.7.3 (with release binaries, haven't compiled it myself)
- **OS**: Linux Manjaro (LLVM 15.0.7, DRM 3.52, 6.3.5-2-MANJARO)
- **Kernel**: 6.3.5
- **GPU**: AMD Radeon RX 7900 XT (amdgpu drivers)
- **CPU**: Ryzen 9 3900X
- **RAM**: 64GB

**Comment by akb825** [comment]
The issue here is that the DDS file format doesn't differentiate between BC1_RGB and BC1_RGBA formats, so it's up to the renderer to interpret whether the block can contain alpha or not. The BC1 format allows for 1 extra bit of information in addition to the color within each block; BC1_RGB vs. BC1_RGBA chooses whether that extra bit is used to treat the pixel as black or transparent. In most cases the results should be equivalent, but if you know ahead of time there will be no alpha using that extra bit to encode black can give you better visual results in some situations.

Based on what you're observing, RenderDoc most likely interprets the data as BC1_RGBA, which is historically the most common based on its DIrectX origins. (the legacy DXT1 format always considered the texture as having 1-bit alpha) As a result, since BC1_RGB was chosen for encoding, portions of the image used the extra bit of information to mark black pixels, while RenderDoc instead interpreted them as transparent.

If BC1_RGB vs BC1_RGBA is important to you, KTX files support this differentiation natively, while PVR files contain custom metadata to note the distinction. (see README.md for the exact metadata written) Otherwise it's up to the renderer to choose one, or the shader could treat "alpha == 0 means black" to allow for the image quality improvements of BC1_RGB even if the renderer assumes BC1_RGBA. If you'd prefer for maximum compatibility, the visual impact of always choosing BC1_RGBA should be marginal for nearly all non-contrived situations.

**Comment by Froyok** [comment]
I mentioned RenderDoc but other software/framework I'm working with display the same issue under OpenGL.
I'm fine with going with BC1_RGBA, the footprint seems to be the same. Just wanted to be sure if that was the expected behavior.

I'm closing since that answer my question. Thank you for the quick reply ! :)
