### ISSUE TITLE
Consider providing releases with /MT flag :o)

### ISSUE THREAD

**Issue by r-lyeh** [akb825/Cuttlefish#24]
Hello,

Fresh Windows installations cannot run Cuttlefish out of the box, as current win64 binaries/dlls do depend on MSVC C/C++ redistributables, which can be checked like this:

`for /R %i in (*.exe;*.dll) do dumpbin /dependents %i | find /i "vcr"`

Please consider adding this flag `-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded -DCMAKE_POLICY_DEFAULT_CMP0091=NEW` to enable /MT in further releases. 

Tested locally only :o)

https://github.com/akb825/Cuttlefish/blob/024bc57177774034cc77e66f69ac9fbfe36fab53/.github/workflows/main.yml#L292

PS: Keep up the good work! :D

**Comment by akb825** [comment]
I assume you mainly care about the CLI tool in terms of being able to run without the redistributable installed?

The current pre-built packages use shared libraries (DLLs on Windows), so using the static runtime will embed it within both the .exe and .dll. If you were to try and link to the library to use the C++ API instead, it also introduces compatibility issues.

I don't mind adding a tool-only package that contains just the CLI tool with static runtime, however. This would statically link the library and not include the .lib/.dll pair or include files. Since it's just a build system change and adjusting the attached binaries, I can put that on the current release.

**Comment by akb825** [comment]
I have adjusted the artifacts on the latest release as I have described with my previous comment, the "full" packages include the libraries and use the dynamic runtime while the "tool" packages use static runtime with only the tool in the zip.

**Comment by r-lyeh** [comment]
thanks! that'll make it :o)
