### ISSUE TITLE
BC1 vs. BC7

### ISSUE THREAD

**Issue by alecazam** [akb825/Cuttlefish#6]
There seems to be a color issue on the BC1 output.   The red and yellows turn green and black.   All encoded textures except the BC1 thumbnails look correct on macOS - so ASTC, BC7, ETC2. I don't think this is 565 vs. 888 issue either.  I know BC1 only has the two endpoints and selectors for 2 other values, so maybe BC7 is just that much better at fitting the 4 colors in the 4x4 block. 

Tiny 4x4 block
![AttribSimple](https://user-images.githubusercontent.com/3750359/92149325-b7c0c380-edd2-11ea-9fe8-51619619d60f.png)

Here's a snapshot of the thumbnails in macOS
![image](https://user-images.githubusercontent.com/3750359/92149361-c4451c00-edd2-11ea-9778-1df572dd3bbe.png)

The commands to generate BC1 vs BC7 for the png.
cuttlefish -f BC1_RGB --srgb -Q high -i AttribSimple.png -o AttribSimpleBC1s.ktx --alpha none
cuttlefish -f BC7 --srgb -Q high -i AttribSimple.png -o AttribSimpleBC7s.ktx --alpha none

I ended up adding a "--resize 8 8 box" to provide a 4x4 BC1 blocks for each corner.

**Comment by akb825** [comment]
I tried all three different compressors available for BC1-3 within Cuttlefish (NVidia's quick compressor, squish, and icbc), including the flags for the highest quality compression, and all get the same result. I also get the same result when using PVRTexTool, which has a BC1 compressor available for their Windows builds.

In my experience, this is the type of image that's most problematic with BC1-3 compression. Since only two 16-bit colors are used for each block, if you have large color variations inside the block it starts to break down. BC7 has more elaborate block compression modes that are better able to handle these situations. Given that multiple compressors give the same results, I'm leaning towards this being a limitation of the format.
