### ISSUE TITLE
Texture::maxMipmapLevels returns (seemingly) incorrect value for non-square images

### ISSUE THREAD

**Issue by Evangel63** [akb825/Cuttlefish#7]
As title. With an attached image of WxH 256x1024 pixels, the returned value from Texture::maxMipmapLevels is 11, however any mipmap levels after 9 has a width of 0. This causes Texture::generateMipmaps to generate mipmaps that have an area of 0 and report that 11 mipmaps were created via Texture::mipLevelCount.

A workaround for this is to call Texture::maxMipLevels with the minimum of the width and height of the image, then pass that into Texture::generateMipmaps, but a better solution would seem to be to patch Texture::maxMipmapLevels to return the minimum of levelCount{Width,Height,Depth} instead of the maximum.

**Comment by akb825** [comment]
Mipmaps are intended to be created until the dimension is 1x1. For non-square textures, the mipmaps will be clamped at size 1, so the mipmap dimensions for a 256 x 1024 would be:
1. 256 x 1024
2. 128 x 512
3. 64 x 256
4. 32 x 128
5. 16 x 64
6. 8 x 32
7. 4 x 16
8. 2 x 8
9. 1 x 4
10. 1 x 2
11. 1 x 1

I tested with a 256 x 1024 input image and confirmed I'm getting the expected results. This should be the expected behavior for all graphics APIs. (see a similar example on [OpenGL's wiki](https://www.khronos.org/opengl/wiki/Texture#Mip_maps))

Did you see Cuttlefish attempt to create an image with a width of 0 or is this based on custom math by dividing each level until the dimension reached 0?

**Comment by Evangel63** [comment]
You are correct. Didn't realise that.
